from backend import DataFetcher
from ai_engine import TrendPredictor
from database import DataBaseManager

class InvestmentAdvisor:
    def __init__(self, risk_profile="Moderate", investment_amount=1000.0):
        """
        Constructor: Initializes the user settings and the core modules.
        """
        self.risk_profile = risk_profile
        self.amount = investment_amount
        
        # Initialization of the core classes
        self.fetcher = DataFetcher()
        self.predictor = TrendPredictor()
        self.db = DataBaseManager()

    def generate_advice(self, symbol):
        """
        The main method which is called by the UI.
        Organizes the application flow: Data -> AI -> DB -> Advice.
        """
        # 1. Download Data from the API
        df = self.fetcher.get_data(symbol, days='max') # Make sure days='max' is set in fetcher
        if df.empty:
            return {"error": "Αδυναμία λήψης δεδομένων από το API."}

        # 2. Train AI and Generate Predictions
        self.predictor.train(df)
        prediction = self.predictor.predict_future(df)
        current_price = df['close'].iloc[-1]

        # Calculate main percentage change
        change_pct = ((prediction['target_price'] - current_price) / current_price) * 100

        # 3. Log the prediction result in the Database
        self.db.log_prediction(symbol, current_price, prediction)

        # 4. Produce final human-friendly advice based on the risk profile
        advice_text = self._logic_engine(prediction, current_price)
        
        # Integrate Macro Analysis text generated by the predictor
        if 'macro_text' in prediction:
            advice_text += prediction['macro_text']
        
        return {
            "symbol": symbol,
            "current_price": round(current_price, 2),
            "prediction": prediction, 
            "advice": advice_text,
            "error_margin": prediction['mae'],
            "time_limit": prediction['time_horizon'],
            "price_change_pct": round(change_pct, 2)
        }

    def _logic_engine(self, prediction, current_price):
        """
        Decision Support Logic: Transforms the calculated numbers to human-friendly advice.
        Utilizes a natural and direct tone.
        """
        target = prediction['target_price']
        signal = prediction['signal']
        horizon = prediction['time_horizon']
        
        # Calculate percentage change for logic gates
        price_diff_pct = ((target - current_price) / current_price) * 100
        
        # --- ERROR HANDLING (Very large MAE indicates high volatility/uncertainty) ---
        if prediction.get('mae', 0) > current_price * 0.15:
            return "🤔 Τα πράγματα είναι αρκετά ρευστά αυτή τη στιγμή. Το μοντέλο μου δυσκολεύεται να βγάλει ασφαλές συμπέρασμα λόγω της μεγάλης αστάθειας. Καλύτερα να μείνουμε εκτός προς το παρόν και να το ξαναδούμε αργότερα."

        # --- 1. STRONG BULLISH > 3% ---
        if price_diff_pct > 3.0:
            if self.risk_profile == "Aggressive":
                return (f"🚀 Τα δεδομένα δείχνουν ξεκάθαρη εκτόξευση! Προβλέπεται ένα δυνατό ράλι προς τα ${target:,.2f} μέσα στις επόμενες {horizon}. "
                        f"Αν σου αρέσει το ρίσκο, αυτή είναι μια εξαιρετική στιγμή για να μπεις δυναμικά στο παιχνίδι.")
            elif self.risk_profile == "Moderate":
                return (f"📈 Έχουμε μια πολύ ωραία ανοδική τάση μπροστά μας, με στόχο τα ${target:,.2f}. "
                        f"Είναι μια καλή ευκαιρία να χτίσεις σταδιακά τη θέση σου, χωρίς υπερβολές. Κάνε την κίνησή σου μέσα στις επόμενες {horizon}.")
            else: # Conservative
                return (f"✅ Η αγορά δείχνει πολύ θετικά σημάδια για μια κίνηση προς τα ${target:,.2f}. "
                        f"Μπορείς να τοποθετηθείς με ασφάλεια, αλλά πάντα να θυμάσαι να βάλεις ένα όριο ζημιάς (stop-loss) για να έχεις το κεφάλι σου ήσυχο.")

        # --- 2. MILD BULLISH 0.5% to 3.0% ---
        elif 0.5 < price_diff_pct <= 3.0:
            if self.risk_profile == "Aggressive":
                return (f"⚡ Υπάρχει ένα μικρό παραθυράκι για γρήγορο κέρδος προς τα ${target:,.2f}. "
                        f"Δεν είναι για 'χοντρά' παιχνίδια, αλλά αν παρακολουθείς στενά την οθόνη, είναι μια καλή ευκαιρία για τις επόμενες {horizon}.")
            else: # Moderate & Conservative
                return (f"📊 Φαίνεται μια ελαφριά άνοδος προς τα ${target:,.2f}, αλλά τίποτα το ακραίο. "
                        f"Προσωπικά, θα πρότεινα να κρατήσεις αυτά που ήδη έχεις (HOLD) και να μην ανοίξεις μεγάλες νέες θέσεις ακόμα.")

        # --- 3. STRONG BEARISH < -3% ---
        elif price_diff_pct < -3.0:
            if self.risk_profile == "Aggressive":
                return (f"🩸 Προσοχή, έρχεται γερή βουτιά προς τα ${target:,.2f}. "
                        f"Αν παίζεις επιθετικά, ίσως είναι η ώρα να εκμεταλλευτείς την πτώση (Short). Αλλιώς, μάζεψε τα κέρδη σου και βγες γρήγορα.")
            elif self.risk_profile == "Moderate":
                return (f"⚠️ Τα πράγματα ζορίζουν. Η αγορά φαίνεται να διορθώνει απότομα προς τα ${target:,.2f}. "
                        f"Καλό θα ήταν να μειώσεις λίγο το ρίσκο σου και να κλειδώσεις κάποια κέρδη πριν περάσουν οι επόμενες {horizon}.")
            else: # Conservative
                return (f"🛡️ Κόκκινος συναγερμός. Η τάση είναι ξεκάθαρα πτωτική. Η πιο συνετή κίνηση είναι να κλείσεις τις θέσεις σου τώρα "
                        f"και να περιμένουμε να ηρεμήσει η αγορά γύρω στα ${target:,.2f}.")

        # --- 4. MILD BEARISH -0.5% to -3.0% ---
        elif -3.0 <= price_diff_pct < -0.5:
            if self.risk_profile == "Aggressive":
                return (f"📉 Περιμένουμε μια μικρή υποχώρηση στα ${target:,.2f} μέσα στις επόμενες {horizon}. "
                        f"Μην αγχωθείς, απλά περίμενε να πιάσει πάτο αυτή η μικρή διόρθωση και αγόρασε φθηνότερα (Buy the dip).")
            else: # Moderate & Conservative
                return (f"⚖️ Η αγορά δείχνει λίγο κουρασμένη και ίσως 'τσιμπήσει' λίγο προς τα κάτω (${target:,.2f}). "
                        f"Μην κάνεις σπασμωδικές κινήσεις. Κράτα την ψυχραιμία σου, διατήρησε τη στρατηγική σου και απλά παρακολούθησέ το.")

        # --- 5. ACCUMULATION / NEUTRAL -0.5% to 0.5% ---
        else:
            if "BULLISH" in signal:
                return (f"🔍 Είμαστε σχεδόν στο μηδέν από άποψη μεταβολής, αλλά βλέπω ένα θετικό τεχνικό μοτίβο να σχηματίζεται. "
                        f"Η αγορά μάλλον μαζεύει δυνάμεις. Έχε το νου σου στις επόμενες {horizon}, ίσως σκάσει κάτι καλό σύντομα.")
            else:
                return (f"🧭 Απόλυτη ησυχία. Η αγορά είναι εντελώς στάσιμη αυτή τη στιγμή. "
                        f"Δεν αξίζει να ρισκάρουμε χωρίς λόγο. Ας κάνουμε ένα διάλειμμα και το ξαναβλέπουμε αργότερα.")